sudo: required
dist: focal
language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38
  - python: 3.9
    env: TOXENV=py39
cache:
  directories:
  - $TRAVIS_BUILD_DIR/ffmpeg
install:
- pip install -q tox
- pip install -q coveralls
- pip install -q sphinx>=1.3 sphinx_rtd_theme
before_script:
# Install ffmpeg
- mkdir -p ffmpeg
- wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz.md5 -O ffmpeg-new.md5
- if ! diff -q ffmpeg-new.md5 ffmpeg/ffmpeg.md5 2>/dev/null; then
    rm -Rf ffmpeg/*;
    wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz.md5 -O ffmpeg/ffmpeg.md5;
    wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz;
    tar xf ffmpeg-release-amd64-static.tar.xz --strip-components 1 -C ffmpeg;
  fi
- export PATH=$TRAVIS_BUILD_DIR/ffmpeg:$PATH
- ffprobe -formats
- ffprobe -codecs
- ffprobe -pix_fmts
script:
- pip install .
- tox -e $TOXENV
- py.test --doctest-modules madam
- sphinx-build -b html doc/ doc/_build/html
after_success:
- test $TOXENV = "py39" && coveralls
before_deploy:
- pip install wheel
- python setup.py bdist_wheel
deploy:
  provider: pypi
  user: eseifert
  password:
    secure: q7r+zIDG+m7qrXFC/Cn2TaPXhSU9cnE+1m8j6smMlKfuNYcp1K56RYOzTn7TQgURLGaVhsw1ZpcB4ib1kt7uVvBMZD+gaMsZ3rSfF0wA+OjY/aUUHc3SP/n8JHexdTmrQJVVrX1yegoHRtl5JtApKbPRx6TTBdoPzJY70+R94PcIdM0Y1+MlHrAmvOsHUrBPt6uC/bfbE70/RkNStNBVFX3NpExi3+0VFqDtNpBkXBRs1Yot1l/pQCyKgHkm3mJMmBk8kv4mASOJSIOokv3IQb7vDx+G1jTyf7NCadkZLn9OJtBcd5CSL4kDBo3p61zprZptg4XW0zFbqWr2FKTEqGWEN/CSgF4GmCS25iTfkMLKjrYp4vD8hIHhW2q/GM/0fs8yuepljUeXgRiIYBI5DCx1I9TG2Yd8oENDUe3uJvSCaSsWr1QeB0NMlpZUo0fKsjhTzCFdTUnbsUhpyQVEVXa4nEz12ogXLllH5atvCV/kYoUHKGj36GCIsY98oD4DycKany3VQDGJGrv/TsfSrCMny1MVysPRvosdyOCACPUyawqTqJawKZS/DVRePfHaSnpY4X111BOf7vJkQVUOM4Xpsw0hirRTdrG7m0OGYxVzQUXl8z7FcDRVDiPpPJJKkZM/kWKeFOHG3MJGA4S8bFSMiIBRK6vGdGKq0/coiRs=
  on:
    tags: true
    condition: $TOXENV = "py39"
  repo: eseifert/madam
  distributions: sdist bdist_wheel
  skip_cleanup: true
