name: CI

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: 3.7
            tox-env: py37
          - python-version: 3.8
            tox-env: py38
          - python-version: 3.9
            tox-env: py39
          - python-version: 3.10
            tox-env: py310

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -q tox
          pip install -q coveralls
          pip install -q sphinx>=1.3 sphinx_rtd_theme
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          ffprobe -formats
          ffprobe -codecs
          ffprobe -pix_fmts
      - name: Test package
        run: |
          pip install .
          tox -e ${{ matrix.tox-env }}
          py.test --doctest-modules madam
          sphinx-build -b html doc/ doc/_build/html
      - name: Measure coverage
        if: ${{ matrix.python-version == '3.10' }}
        run: |
          coveralls
